window.SONGS = [
  {title:"57 Years", section:"family", file:"music/57-years.mp3", dur:338},
  {title:"A Match Made in Heaven (Happy Birthday, Tracey)", section:"family", file:"music/match-made-tracey.mp3", dur:118},
  {title:"Addison Faith", section:"family", file:"music/addison-faith.mp3", dur:209},
  {title:"Happy Birthday, Brendan", section:"family", file:"music/hb-brendan.mp3", dur:167},
  {title:"Happy Birthday, Brianna", section:"family", file:"music/hb-brianna.mp3", dur:101},
  {title:"Happy Birthday, Sandra", section:"family", file:"music/hb-sandra.mp3", dur:187},
  {title:"Lindsey B — Batteries", section:"family", file:"music/lindsey-batteries.mp3", dur:45},
  {title:"Living the Dream", section:"family", file:"music/living-the-dream.mp3", dur:176},
  {title:"Memorial Day (for Stormy)", section:"family", file:"music/memorial-stormy.mp3", dur:275},
  {title:"The Greendale Queen", section:"family", file:"music/greendale-queen.mp3", dur:187},
  {title:"Two Pillars", section:"family", file:"music/two-pillars.mp3", dur:320},
  {title:"Unconditional", section:"family", file:"music/unconditional.mp3", dur:254},
  {title:"No Matter What", section:"family", file:"music/no-matter-what.mp3", dur:266},
  {title:"Detours", section:"family", file:"music/detours.mp3", dur:144},
  {title:"Cipa Cipa", section:"family", file:"music/cipa-cipa.mp3", dur:97},
  {title:"Huddle Up (Tom Saylor)", section:"family", file:"music/huddle-up.mp3", dur:195},
  {title:"Angel for God", section:"faith", file:"music/angel-for-god.mp3", dur:213},
  {title:"Be the Reason", section:"faith", file:"music/be-the-reason.mp3", dur:179},
  {title:"For Such a Time as This", section:"faith", file:"music/for-such-a-time.mp3", dur:260},
  {title:"I Am Yours", section:"faith", file:"music/i-am-yours.mp3", dur:257},
  {title:"In Christ", section:"faith", file:"music/in-christ.mp3", dur:209},
  {title:"Let God Be God (Jazz Edition)", section:"faith", file:"music/let-god-jazz.mp3", dur:275},
  {title:"Let God Be God (Piano Duet)", section:"faith", file:"music/let-god-piano.mp3", dur:284},
  {title:"Not My Will", section:"faith", file:"music/not-my-will.mp3", dur:158},
  {title:"Not My Will, but Yours Be Done", section:"faith", file:"music/not-my-will-yours.mp3", dur:274},
  {title:"You Matter to Christ", section:"faith", file:"music/you-matter.mp3", dur:175},
  {title:"You Matter to Christ (Original)", section:"faith", file:"music/you-matter-original.mp3", dur:202},
  {title:"Zeteo", section:"faith", file:"music/zeteo.mp3", dur:238},
  {title:"159 Years Strong (Zion Baptist Song)", section:"faith", file:"music/159-years-strong.mp3", dur:404},
];
